---
stages:
  - lint
  - unit
  - functional

lint:
  stage: lint
  tags:
    - docker
  image: 'python:3.6'
  script:
    - tox -e lint
    - tox -e lintjunit
  artefacts:
    paths:
      - report/lint
  reports:
    junit: report/lint/junit.xml

unit:
  stage: unit
  tags:
    - docker
  image: 'python:3.6'
  script:
    - tox -e unit
  artefacts:
    paths:
      - report/unit
  reports:
    junit: report/unit/junit.xml

functional:
  stage: functional
  tags:
    - docker
  image: 'python:3.6'
  script:
    - tox -e functional
  artefacts:
    paths:
      - report/functional
  reports:
    junit: report/functional/junit.xml
