---
image: 'python:3.6'

stages:
  - test

before_script:
  - python --version
  - pip install tox
  - mkdir -p report/lint
  - mkdir -p report/unit

flake8:
  stage: test
  script:
    - tox -e lint
  artifacts:
    paths:
      - report/lint

pytest:
  stage: test 
  script:
    - tox -e unit
  artifacts:
    paths:
      - report/unit
