---
image: 'python:3.6'

stages:
  - test

lint:
  stage: test
  script:
    - pip install tox
    - tox -e lint
    - tox -e lintjunit
  artifacts:
    paths:
      - report/lint
    reports:
      junit: report/lint/junit.xml

unit:
  stage: test 
  script:
    - pip install tox
    - tox -e unit
  artifacts:
    paths:
      - report/unit
    reports:
      junit: report/unit/junit.xml

functional:
  stage: test
  script:
    - pip install tox
    - tox -e functional
  artifacts:
    paths:
      - report/functional
    reports:
      junit: report/functional/junit.xml
