options:
  version:
    type: string
    default: ""
    description: "The version of GitLab to install. Defaults (when this setting is empty) to latest."
  apt_key:
    type: string
    default: "14219A96E15E78F4"
    description: "The APT signing key used for the repository specified by apt_repo"
  apt_repo:
    type: string
    default: "https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/"
    description: "The APT source repository to configure before installing GitLab. The Ubuntu distribution (i.e. 'bionic' and the component 'main') will be automatically appended to the provided URI"
  external_url:
    type: string
    default: ""
    description: "The external URI of this GitLab install. This will be used to configure GitLab, and any reverse proxy configured via the reverseproxy relation. Defaults to the fqdn of the unit."
  http_port:
    type: int
    default: 80
    description: "The HTTP port the GitLab backend will listen for connections on. It is recommended to relate this charm to a reverse proxy, rather than customising this value"
  ssh_port:
    type: int
    default: 222
    description: "The external TCP port over which SSH-based git clone operations will be available, when GitLab is related to an external load balancer via the reverseproxy relation. Without a reverseproxy relation, the system sshd is used on port 22."
  package_name:
    type: string
    default: gitlab-ce
    description: "The package to use. Options are gitlab-ce for the FOSS version of gitlab-ee for the Enterprise Edition."
