options:
  version:
    type: string
    default: ""
    description: "The version of GitLab to install. Defaults (when this setting is empty) to latest."
  apt_key:
    type: string
    default: "14219A96E15E78F4"
    description: "The APT signing key used for the repository specified by apt_repo"
  apt_repo:
    type: string
    default: "https://packages.gitlab.com/gitlab"
    description: "The APT source repository to configure before installing GitLab. The Ubuntu distribution, component, /ubuntu suffix, as well as package type (gitlab-ce/gitlab-ee) will be appended. e.g. gitlab-ce/ubuntu bionic main"
  external_url:
    type: string
    default: ""
    description: "The external URI of this GitLab install. This will be used to configure GitLab, and any reverse proxy configured via the reverseproxy relation. Defaults to the fqdn of the unit."
  http_port:
    type: int
    default: 80
    description: "The HTTP port the GitLab backend will listen for connections on. It is recommended to relate this charm to a reverse proxy, rather than customising this value"
  ssh_port:
    type: int
    default: 222
    description: "The external TCP port over which SSH-based git clone operations will be available, when GitLab is related to an external load balancer via the reverseproxy relation. Without a reverseproxy relation, the system sshd is used on port 22."
  package_name:
    type: string
    default: "gitlab-ce"
    description: "The package to use. Options are gitlab-ce for the FOSS version of gitlab-ee for the Enterprise Edition."
  runners_bypass_proxy:
    type: boolean
    default: False
    description: "Register runners with fqdn even if a proxy is in use. The default value of False will register runners through the reverseproxy if present."
  proxy_via_ip:
    type: boolean
    default: False
    description: "Register IP rather than FQDN with the reverseproxy to support environments without DNS resolution of the host."
  smtp_server:
    type: string
    default: ""
    description: "Set the external SMTP host to use when sending emails from GitLab. If unset, will default to local MTA."
  smtp_port:
    type: int
    default: 25
    description: "When using external SMTP, this setting allows you to customise the TCP port used to connect to the SMTP server."
  smtp_user:
    type: string
    default: ""
    description: "If both smtp_user and smtp_password are set, authentication will be used with the provided credentials when connecting to the configured external SMTP server."
  smtp_password:
    type: string
    default: ""
    description: "If both smtp_user and smtp_password are set, authentication will be used with the provided credentials when connecting to the configured external SMTP server."
  smtp_domain:
    type: string
    default: ""
    description: "The domain to use when sending email from GitLab. Will default to the server name, influenced by the external URL configured."
  smtp_authentication:
    type: string
    default: "login"
    description: "Used to override the authentication method to use when external SMTP is in use."
  smtp_tls:
    type: boolean
    default: false
    description: "Set this to true to enable TLS when connecting to the configured external SMTP server."
